import 'dart:convert';
import 'dart:io';
// import 'package:amigos_fuel_ur_future/model/AllCousesModel.dart';
// import 'package:amigos_fuel_ur_future/model/AllEventsModel.dart';
// import 'package:amigos_fuel_ur_future/model/BlogModel.dart';
// import 'package:amigos_fuel_ur_future/model/BootCampModel.dart';
// import 'package:amigos_fuel_ur_future/model/ContactUsModel.dart';
// import 'package:amigos_fuel_ur_future/model/ImageModal.dart';
// import 'package:amigos_fuel_ur_future/model/LoginModel.dart';
// import 'package:amigos_fuel_ur_future/model/NotificationModel.dart';
// import 'package:amigos_fuel_ur_future/model/PrivacyPolicyModel.dart';
// import 'package:amigos_fuel_ur_future/model/ProfileModel.dart';
// import 'package:amigos_fuel_ur_future/model/ResultModel.dart';
// import 'package:amigos_fuel_ur_future/model/TestimonialModel.dart';
// import 'package:http/http.dart' as https;
// import 'package:shared_preferences/shared_preferences.dart';